/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HasilRouteImport } from './routes/hasil'
import { Route as KesimpulanRouteImport } from './routes/kesimpulan'
import { Route as LandasanTeoriRouteImport } from './routes/landasan-teori'
import { Route as MetodeRouteImport } from './routes/metode'
import { Route as PendahuluanRouteImport } from './routes/pendahuluan'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HasilRoute = HasilRouteImport.update({
  id: '/hasil',
  path: '/hasil',
  getParentRoute: () => rootRouteImport,
} as any)
const KesimpulanRoute = KesimpulanRouteImport.update({
  id: '/kesimpulan',
  path: '/kesimpulan',
  getParentRoute: () => rootRouteImport,
} as any)
const LandasanTeoriRoute = LandasanTeoriRouteImport.update({
  id: '/landasan-teori',
  path: '/landasan-teori',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodeRoute = MetodeRouteImport.update({
  id: '/metode',
  path: '/metode',
  getParentRoute: () => rootRouteImport,
} as any)
const PendahuluanRoute = PendahuluanRouteImport.update({
  id: '/pendahuluan',
  path: '/pendahuluan',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hasil': typeof HasilRoute
  '/kesimpulan': typeof KesimpulanRoute
  '/landasan-teori': typeof LandasanTeoriRoute
  '/metode': typeof MetodeRoute
  '/pendahuluan': typeof PendahuluanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hasil': typeof HasilRoute
  '/kesimpulan': typeof KesimpulanRoute
  '/landasan-teori': typeof LandasanTeoriRoute
  '/metode': typeof MetodeRoute
  '/pendahuluan': typeof PendahuluanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hasil': typeof HasilRoute
  '/kesimpulan': typeof KesimpulanRoute
  '/landasan-teori': typeof LandasanTeoriRoute
  '/metode': typeof MetodeRoute
  '/pendahuluan': typeof PendahuluanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hasil'
    | '/kesimpulan'
    | '/landasan-teori'
    | '/metode'
    | '/pendahuluan'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hasil'
    | '/kesimpulan'
    | '/landasan-teori'
    | '/metode'
    | '/pendahuluan'
  id:
    | '__root__'
    | '/'
    | '/hasil'
    | '/kesimpulan'
    | '/landasan-teori'
    | '/metode'
    | '/pendahuluan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HasilRoute: typeof HasilRoute
  KesimpulanRoute: typeof KesimpulanRoute
  LandasanTeoriRoute: typeof LandasanTeoriRoute
  MetodeRoute: typeof MetodeRoute
  PendahuluanRoute: typeof PendahuluanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hasil': {
      id: '/hasil'
      path: '/hasil'
      fullPath: '/hasil'
      preLoaderRoute: typeof HasilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kesimpulan': {
      id: '/kesimpulan'
      path: '/kesimpulan'
      fullPath: '/kesimpulan'
      preLoaderRoute: typeof KesimpulanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landasan-teori': {
      id: '/landasan-teori'
      path: '/landasan-teori'
      fullPath: '/landasan-teori'
      preLoaderRoute: typeof LandasanTeoriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metode': {
      id: '/metode'
      path: '/metode'
      fullPath: '/metode'
      preLoaderRoute: typeof MetodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pendahuluan': {
      id: '/pendahuluan'
      path: '/pendahuluan'
      fullPath: '/pendahuluan'
      preLoaderRoute: typeof PendahuluanRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HasilRoute: HasilRoute,
  KesimpulanRoute: KesimpulanRoute,
  LandasanTeoriRoute: LandasanTeoriRoute,
  MetodeRoute: MetodeRoute,
  PendahuluanRoute: PendahuluanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
